myblogapp/urls.py
from django.urls import path

from . import views
from .views import IndexView, PostDetailView, CategoryListView, TagListView, CategoryPostView, TagPostView

app_name = 'myblog'

urlpatterns = [
  path('', IndexView.as_view(), name='index'),
  path('contact/', views.contact, name='contact'),
  path('contact/complete/', views.complete, name='complete'),
  path('post/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
  path('categories/', CategoryListView.as_view(), name='category_list'),
  path('tags/', TagListView.as_view(), name='tag_list'),
  path('category/<str:category_slug>/',CategoryPostView.as_view(), name='category_post'),
  path('tag/<str:tag_slug>/', TagPostView.as_view(), name='tag_post'),
]

myblogproject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('myblog/', include('myblogapp.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myblogapp/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Post(models.Model):
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    tags = models.ManyToManyField(Tag, blank=True)
    title = models.CharField(max_length=255)
    content = models.TextField()
    description = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    published_at = models.DateTimeField(blank=True, null=True)
    is_public = models.BooleanField(default=False)
    image = models.ImageField(upload_to='post_images/', null=True, blank=True)

    class Meta:
        ordering = ['-created_at']

    def save(self, *args, **kwargs):
        if self.is_public and not self.published_at:
            self.published_at = timezone.now()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

class ContentImage(models.Model):
    post = models.ForeignKey(Post, on_delete=models.PROTECT)
    content_image = models.ImageField(upload_to='post_content_images/')

myblogapp/forms.py
from django import forms

class Contact(forms.Form):
  subject = forms.CharField(label='お名前', max_length=100)
  sender = forms.EmailField(label='Email', help_text='※ご確認の上、正しくご入力ください。')
  message = forms.CharField(label='お問い合わせ内容', widget=forms.Textarea)
  myself = forms.BooleanField(label='同じ内容を受け取る', required=False)

myblogapp/views.py
from django.shortcuts import render, redirect
from .forms import Contact
from django.http import HttpResponse
from django.conf import settings
from django.core.mail import BadHeaderError, send_mail
from django.db.models import Count, Q
from django.http import Http404
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.shortcuts import get_object_or_404

from .models import Post, Category, Tag

# Create your views here.

def index(request):
  return render(request, 'myblog/index.html')

def contact(request):
  return render(request, 'myblog/contact.html')

def complete(request):
    return render(request, 'myblog/complete.html')

def contact(request):
    if request.method == 'POST':
        form = Contact(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            sender = form.cleaned_data['sender']
            myself = form.cleaned_data['myself']
            recipients = [settings.EMAIL_HOST_USER]
            if myself:
                recipients.append(sender)
            try:
                send_mail(subject, message, sender, recipients)
            except BadHeaderError:
                return HttpResponse('無効なヘッダーが見つかりました。')
            return redirect('myblog:complete')
    else:
        form = Contact()
    return render(request, 'myblog/contact.html', {'form': form})


class  PostDetailView(DetailView):
  template_name = 'myblog/post_detail.html'
  model = Post

  def get_object(self, queryset=None):
    obj = super().get_object(queryset=queryset)
    if not obj.is_public and not self.request.user.is_authenticated:
      raise Http404
    return obj

class IndexView(ListView):
  model = Post
  template_name = 'myblog/index.html'

  paginate_by = 3

class CategoryListView(ListView):
  template_name = 'myblog/category_list.html'
  queryset = Category.objects.annotate(
    num_posts=Count('post', filter=Q(post__is_public=True)))
  
class TagListView(ListView):
  template_name = 'myblog/tag_list.html'
  queryset = Tag.objects.annotate(num_posts=Count(
    'post', filter=Q(post__is_public=True)))

class CategoryPostView(ListView):
    model = Post
    template_name = 'myblog/category_post.html'

    def get_queryset(self):
        category_slug = self.kwargs['category_slug']
        self.category = get_object_or_404(Category, slug=category_slug)
        qs = super().get_queryset().filter(category=self.category)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = self.category
        return context


class TagPostView(ListView):
    model = Post
    template_name = 'myblog/tag_post.html'

    def get_queryset(self):
        tag_slug = self.kwargs['tag_slug']
        self.tag = get_object_or_404(Tag, slug=tag_slug)
        qs = super().get_queryset().filter(tags=self.tag)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tag'] = self.tag
        return context

myblogapp/templates/myblog/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=10.0">
    <title>yusuke.blog</title>
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <meta http-equiv="Content-Script-Type" content="text/javascript">
  </head>

  <body>
    
    <div id="my-spinner" class="box-name">
      <div class="spinner type1">
        <span>MuramatsuYusuke</span>
      </div>
    </div>

    <div class="shutter"></div>
 
    <section class="container">
    </section>

    <header>
      <div id="fixed">
        <div class="sp_menu">
          <span class="logo">YUSUKE.BLOG</span>
          <a href="{% url 'myblog:contact' %}" class="reservation "><img class="pc_content" src="{% static 'myblog/contact.png' %}" alt="contact"><img class="sp_content" src="" alt=""></a>
          
          <div id="hamburger">
            <div class="menu-trigger">
              <span></span>
              <span></span>
              <span></span>
             </div>
          </div>
           <div id="blind_menu">
             <ul id="menu_list_sp" style="padding: 0;">
               <li class="menu_item">
                 <a href="#" class="menu-list">About</a>
               </li>
               <li class="menu_item">
                 <a href="#works" class="menu-list">Portfolio</a>
               </li>
               <li class="menu_item">
                 <a href="#blog" class="menu-list">Blog</a>
               </li>
               <li class="menu_item">
                 <a href="{% url 'myblog:contact' %}"  class="menu-list">Contact</a>
               </li>
             </ul>
           </div>
          </div>

      </div>
    </header>
    <div id="side_menu" class="pc_content">
      <div>
        <a href="#">top</a>
        <a href="#works">Portfolio</a>
        <a href="#blog">Blog</a>
        <a href="#insta_area">Instagram</a>
      </div>
    </div>
    <main>
      {% block content %}
      {% endblock %}
    </main>
    <footer style="padding:150px 0 210px; text-align: center; font-size:10px;">
      <p class="all_rights">2020.04.24  MuramatsuYusuke.</p>
    </footer>
  <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://unpkg.com/scrollreveal@4.0.0/dist/scrollreveal.min.js"></script>
  <script src="{% static 'js/index.js' %}"></script>

  </body>

</html>

myblogapp/templates/myblog/category_list.html
{% load static %}
<head>
  <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=10.0">
  <title>yusuke.blog</title>
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
  <meta http-equiv="Content-Script-Type" content="text/javascript">
</head>
<header>
  <div id="fixed">
    <div class="sp_menu">
      <span class="logo">YUSUKE.BLOG</span>
      <a href="{% url 'myblog:contact' %}" class="reservation "><img class="pc_content" src="{% static 'myblog/contact.png' %}" alt="contact"><img class="sp_content" src="" alt=""></a>
      
      <div id="hamburger">
        <div class="menu-trigger">
          <span></span>
          <span></span>
          <span></span>
         </div>
      </div>
       <div id="blind_menu">
         <ul id="menu_list_sp" style="padding: 0;">
           <li class="menu_item">
             <a href="../../../myblog/" class="menu-list">Top</a>
           </li>
           <li class="menu_item">
             <a href="./index.php" class="menu-list">About</a>
           </li>
           <li class="menu_item">
             <a href="./here.php" class="menu-list">Portfolio</a>
           </li>
           <li class="menu_item">
             <a href="../../../myblog/#blog" class="menu-list">Blog</a>
           </li>
           <li class="menu_item">
             <a href="{% url 'myblog:contact' %}"  class="menu-list">Contact</a>
           </li>
         </ul>
       </div>
      </div>

  </div>
</header>



<section id="blog" class="cf" style="width: 1100px; display: flex;">
  <div class="blog-main">
    <h1>カテゴリ一覧</h1>
    <ul>
      {% for category in object_list %}
      <li><a href="{% url 'myblog:category_post' category.slug %}">{{ category.name }} ({{ category.num_posts }})</a></li>
      {% empty %}
      <li>カテゴリはありません。</li>
      {% endfor %}
    </ul>
  </div>

    <div class="container">
      <div class="row">
        <main class="col-md-8">
          <h1 class="mb-4">投稿一覧</h1>
          
        </main>
        <aside class="col-md-4">
          {% include "myblogapp/templates/snippets/sidebar.html" %}
        </aside>
      </div>
    </div>
  
</section>
  
  





<footer style="padding:150px 0 210px; text-align: center; font-size:10px;">
  <p class="all_rights">Copyright © 2019  All Rights Reserved.</p>
</footer>
<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://unpkg.com/scrollreveal@4.0.0/dist/scrollreveal.min.js"></script>
<script src="{% static 'js/index.js' %}"></script>

myblogapp/templates/myblog/category_post.html
{% load static %}
<head>
  <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=10.0">
  <title>yusuke.blog</title>
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
  <meta http-equiv="Content-Script-Type" content="text/javascript">
</head>
<header>
  <div id="fixed">
    <div class="sp_menu">
      <span class="logo">YUSUKE.BLOG</span>
      <a href="{% url 'myblog:contact' %}" class="reservation "><img class="pc_content" src="{% static 'myblog/contact.png' %}" alt="contact"><img class="sp_content" src="" alt=""></a>
      
      <div id="hamburger">
        <div class="menu-trigger">
          <span></span>
          <span></span>
          <span></span>
         </div>
      </div>
       <div id="blind_menu">
         <ul id="menu_list_sp" style="padding: 0;">
           <li class="menu_item">
             <a href="../../../myblog/" class="menu-list">Top</a>
           </li>
           <li class="menu_item">
             <a href="./index.php" class="menu-list">About</a>
           </li>
           <li class="menu_item">
             <a href="./here.php" class="menu-list">Portfolio</a>
           </li>
           <li class="menu_item">
             <a href="../../../myblog/#blog" class="menu-list">Blog</a>
           </li>
           <li class="menu_item">
             <a href="{% url 'myblog:contact' %}"  class="menu-list">Contact</a>
           </li>
         </ul>
       </div>
      </div>

  </div>
</header>



<section id="blog" class="cf" style="width: 1100px; display: flex;">
  <div class="blog-main">
    <h1>{{ category.name }}の投稿一覧</h1>
    <ul>
      {% for post in object_list %}
      {% if user.is_authenticated or post.is_public %}
      <li>{% if not post.is_public %}[下書き] {% endif %}<a href="{% url 'myblog:post_detail' post.id %}" class="card-link">{{ post.title }}</a></li>
      {% else %}
      <li>投稿はありません。</li>
      {% endif %}
      {% empty %}
      <li>まだ投稿はありません。</li>
      {% endfor %}
    </ul>
  </div>

    <div class="container">
      <div class="row">
        <main class="col-md-8">
          <h1 class="mb-4">投稿一覧</h1>
          
        </main>
        <aside class="col-md-4">
          {% include "myblogapp/templates/snippets/sidebar.html" %}
        </aside>
      </div>
    </div>
  
</section>
  
  





<footer style="padding:150px 0 210px; text-align: center; font-size:10px;">
  <p class="all_rights">Copyright © 2019  All Rights Reserved.</p>
</footer>
<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://unpkg.com/scrollreveal@4.0.0/dist/scrollreveal.min.js"></script>
<script src="{% static 'js/index.js' %}"></script>

myblogapp/templates/myblog/complete.html
{% extends 'myblog/base.html' %}


{% block content %}

<h1 style="text-align: center;margin: 200px auto 50px;">送信完了</h1>
<a href="{% url 'myblog:index' %}" style="text-decoration: none;">
<p style="text-align: center;text-decoration: none;color: gray;">トップへ</p>
</a>

{% endblock %}

myblogapp/templates/myblog/contact.html
{% load static %} 

<head>
  <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=10.0">
  <title>yusuke.blog</title>
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
  <meta http-equiv="Content-Script-Type" content="text/javascript">
</head>
<header>
  <div id="fixed">
    <div class="sp_menu">
      <span class="logo">YUSUKE.BLOG</span>
      <a href="{% url 'myblog:contact' %}" class="reservation "><img class="pc_content" src="{% static 'myblog/contact.png' %}" alt="contact"><img class="sp_content" src="" alt=""></a>
      
      <div id="hamburger">
        <div class="menu-trigger">
          <span></span>
          <span></span>
          <span></span>
         </div>
      </div>
       <div id="blind_menu">
         <ul id="menu_list_sp" style="padding: 0;">
           <li class="menu_item">
             <a href="../" class="menu-list">Top</a>
           </li>
           <li class="menu_item">
             <a href="./index.php" class="menu-list">About</a>
           </li>
           <li class="menu_item">
             <a href="./here.php" class="menu-list">Portfolio</a>
           </li>
           <li class="menu_item">
             <a href="../../../myblog/#blog" class="menu-list">Blog</a>
           </li>
           <li class="menu_item">
             <a href="{% url 'myblog:contact' %}"  class="menu-list">Contact</a>
           </li>
         </ul>
       </div>
      </div>

  </div>
</header>

{% block content %}
<link href="{% static 'css/contact.css' %}" rel="stylesheet">
<section class="contBox cf" id="contact-form">
  <h2 class="ttl large"style="margin-bottom: 70px;">Contact</h2>
  <p class="txtBox">制作の依頼・ご相談などお気軽にお問い合わせくださいませ。<br>下記フォームよりわかる範囲でご記入ください。必須の項目は必ずご記入お願いします。</p>
          <div role="form" class="wpcf7" id="wpcf7-f147-p8-o1" lang="ja" dir="ltr">
  <div class="screen-reader-response"></div>
  

  <form action="{% url 'myblog:contact' %}" method="post" class="wpcf7-form" novalidate="novalidate">
    {% csrf_token %}
  <table>
      {{ form.as_table }}
  </table><br>
      <input type="submit" value="送信" class="wpcf7-form-control submitBtn">
  </form>



  
  
  
</section>
{% endblock %}

<footer style="padding:150px 0 210px; text-align: center; font-size:10px;">
  <p class="all_rights">Copyright © 2019  All Rights Reserved.</p>
</footer>
<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://unpkg.com/scrollreveal@4.0.0/dist/scrollreveal.min.js"></script>
<script src="{% static 'js/index.js' %}"></script>

myblogapp/templates/myblog/tag_list.html
{% load static %}
<head>
  <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=10.0">
  <title>yusuke.blog</title>
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
  <meta http-equiv="Content-Script-Type" content="text/javascript">
</head>
<header>
  <div id="fixed">
    <div class="sp_menu">
      <span class="logo">YUSUKE.BLOG</span>
      <a href="{% url 'myblog:contact' %}" class="reservation "><img class="pc_content" src="{% static 'myblog/contact.png' %}" alt="contact"><img class="sp_content" src="" alt=""></a>
      
      <div id="hamburger">
        <div class="menu-trigger">
          <span></span>
          <span></span>
          <span></span>
         </div>
      </div>
       <div id="blind_menu">
         <ul id="menu_list_sp" style="padding: 0;">
           <li class="menu_item">
             <a href="../../../myblog/" class="menu-list">Top</a>
           </li>
           <li class="menu_item">
             <a href="./index.php" class="menu-list">About</a>
           </li>
           <li class="menu_item">
             <a href="./here.php" class="menu-list">Portfolio</a>
           </li>
           <li class="menu_item">
             <a href="../../../myblog/#blog" class="menu-list">Blog</a>
           </li>
           <li class="menu_item">
             <a href="{% url 'myblog:contact' %}"  class="menu-list">Contact</a>
           </li>
         </ul>
       </div>
      </div>

  </div>
</header>



<section id="blog" class="cf" style="width: 1100px; display: flex;">
  <div class="blog-main">
    <h1>タグ一覧</h1>
    <ul>
      {% for tag in object_list %}
      <li><a href="{% url 'myblog:tag_post' tag.slug %}" class="card-link">{{ tag.name }} ({{ tag.num_posts }})</a></li>
      {% empty %}
      <li>タグはありません。</li>
      {% endfor %}
    </ul>
  </div>

    <div class="container">
      <div class="row">
        <main class="col-md-8">
          <h1 class="mb-4">投稿一覧</h1>
          
        </main>
        <aside class="col-md-4">
          {% include "myblogapp/templates/snippets/sidebar.html" %}
        </aside>
      </div>
    </div>
  
</section>
  
  





<footer style="padding:150px 0 210px; text-align: center; font-size:10px;">
  <p class="all_rights">Copyright © 2019  All Rights Reserved.</p>
</footer>
<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://unpkg.com/scrollreveal@4.0.0/dist/scrollreveal.min.js"></script>
<script src="{% static 'js/index.js' %}"></script>

myblogapp/templates/myblog/tag_post.html
{% load static %}
<head>
  <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=10.0">
  <title>yusuke.blog</title>
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
  <meta http-equiv="Content-Script-Type" content="text/javascript">
</head>
<header>
  <div id="fixed">
    <div class="sp_menu">
      <span class="logo">YUSUKE.BLOG</span>
      <a href="{% url 'myblog:contact' %}" class="reservation "><img class="pc_content" src="{% static 'myblog/contact.png' %}" alt="contact"><img class="sp_content" src="" alt=""></a>
      
      <div id="hamburger">
        <div class="menu-trigger">
          <span></span>
          <span></span>
          <span></span>
         </div>
      </div>
       <div id="blind_menu">
         <ul id="menu_list_sp" style="padding: 0;">
           <li class="menu_item">
             <a href="../../../myblog/" class="menu-list">Top</a>
           </li>
           <li class="menu_item">
             <a href="./index.php" class="menu-list">About</a>
           </li>
           <li class="menu_item">
             <a href="./here.php" class="menu-list">Portfolio</a>
           </li>
           <li class="menu_item">
             <a href="../../../myblog/#blog" class="menu-list">Blog</a>
           </li>
           <li class="menu_item">
             <a href="{% url 'myblog:contact' %}"  class="menu-list">Contact</a>
           </li>
         </ul>
       </div>
      </div>

  </div>
</header>



<section id="blog" class="cf" style="width: 1100px; display: flex;">
  <div class="blog-main">
    <h1>{{ tag.name }}の投稿一覧</h1>
    <ul>
      {% for post in object_list %}
      {% if user.is_authenticated or post.is_public %}
      <li>{% if not post.is_public %}[下書き] {% endif %}<a href="{% url 'myblog:post_detail' post.id %}" class="card-link">{{ post.title }}</a></li>
      {% else %}
      <li>投稿はありません。</li>
      {% endif %}
      {% empty %}
      <li>まだ投稿はありません。</li>
      {% endfor %}
    </ul>
  </div>

    <div class="container">
      <div class="row">
        <main class="col-md-8">
          <h1 class="mb-4">投稿一覧</h1>
          
        </main>
        <aside class="col-md-4">
          {% include "myblogapp/templates/snippets/sidebar.html" %}
        </aside>
      </div>
    </div>
  
</section>
  
  





<footer style="padding:150px 0 210px; text-align: center; font-size:10px;">
  <p class="all_rights">Copyright © 2019  All Rights Reserved.</p>
</footer>
<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://unpkg.com/scrollreveal@4.0.0/dist/scrollreveal.min.js"></script>
<script src="{% static 'js/index.js' %}"></script>

myblogapp/templates/snippets/sidebar.html
<div class="card mb-3">
  <div class="card-header">
    Category
  </div>
  <ul class="list-group">
    {% for category in categories|dictsort:"id" %}
    <li class="list-group-item" style="display: block; margin: 10px 0 30px; width: 200px; text-align: left;">
      <a href="{% url 'myblog:category_post' category.slug %}" class="card-link">{{ category.name }}</a>
      <span class="badge">{{ category.num_posts }}</span>
    </li>
    {% endfor %}
  </ul>
</div>

<div class="card">
  <div class="card-header">
    Tag
  </div>
  <ul class="list-group">
    {% for tag in tags|dictsortreversed:"num_posts"|slice:":5" %}
    <li class="list-group-item" style="display: block; margin: 10px 0 30px; width: 200px; text-align: left;">
      <a href="{% url 'myblog:tag_post' tag.slug %}" class="card-link">{{ tag.name }}</a>
      <span class="badge">{{ tag.num_posts }}</span>
    </li>
    {% endfor %}
  </ul>
  <div class="card-body text-center">
    <a href="{% url 'myblog:tag_list' %}" class="card-link">すべてのタグを見る</a>
  </div>
</div>